version: "3.9"

services:

  mysql:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: clms_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Backend/sql:/docker-entrypoint-initdb.d

  backend:
    build: ./Backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    env_file:
      - ./Backend/.env
    volumes:
      - ./Backend:/app
      - /app/node_modules

  frontend:
    build: ./Frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://localhost:5000
    volumes:
      - ./Frontend:/app
      - /app/node_modules

volumes:
  mysql_data: